### PR TITLE
add RSS template with full content

### PR DESCRIPTION
**Pull request by maelle**
This template is used for all RSS feed so also the main /index.xml

I added a limit to the number of posts per feed, and a link to the feed in each page (I read somewhere that it's best practice, presumedly to help feed reader find the feed when people try to subscribe to it)

### CODE REVIEW

**Comment by maelle** [comment]
Ideally, try to use https://validator.w3.org/feed/ to validate the feed

**Comment by maelle** [comment]
https://deploy-preview-77--njt-test.netlify.app/index.xml

https://deploy-preview-77--njt-test.netlify.app/categories/newsletter/index.xml

**Comment by maelle** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeploy-preview-77--njt-test.netlify.app%2Fcategories%2Fnewsletter%2Findex.xml

**Comment by njtierney** [comment]
This is simply 🪄  magic 🪄  !

**Pull request merged**
